version: '3.4'

services:
  dockercomposelocalstack:
    image: ${DOCKER_REGISTRY-}dockercomposelocalstack
    depends_on:
      - SqlServer
    build:
      context: .
      dockerfile: DockerComposeLocalStack/Dockerfile
  SqlServer:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433